---
parser: babel-eslint
extends:
  - eslint:recommended
  - plugin:react/recommended
plugins:
  - react-hooks
env:
  browser: true
  node: true
rules:
  react-hooks/rules-of-hooks: error
  quotes:
    - 1
    - single
    - avoid-escape
  prefer-const: 1
  react/jsx-indent:
    - 1
    - 2
  no-return-assign: 1
  no-console: 0
  no-unused-vars:
    - 1
    - vars: all
      args: after-used
      argsIgnorePattern: "^_|^next$"
      varsIgnorePattern: "^_|^log$|^err|^info$|^warn$"
  react/prop-types: 0
